services:
  - type: web
    name: sistema-gestion-docentes
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
